<a href="https://colab.research.google.com/github/SaiRithik24/AD/blob/main/Feature_Engineering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
from pandas import read_csv
from numpy import set_printoptions
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2
import pandas as pd
filename="/content/pima-indians-diabetes.data.csv"
names=['preg','plas','pres','skin','test','mass','pedi','age','class']
dataframe=pd.read_csv(filename,names=names)
array=dataframe.values
X=array[:,0:8]
Y=array[:,8]
test=SelectKBest(score_func=chi2,k=4)
fit=test.fit(X,Y)
set_printoptions(precision=3)
print(fit.scores_)
features=fit.transform(X)

[ 111.52  1411.887   17.605   53.108 2175.565  127.669    5.393  181.304]


In [10]:
from pandas import read_csv
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression

filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = read_csv(filename, names=names)

array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

model = LogisticRegression(max_iter=400)
rfe = RFE(estimator=model, n_features_to_select=3)

fit=rfe.fit(X,Y)

In [11]:
fit.n_features_

3

In [14]:
fit.support_

array([ True, False, False, False, False,  True,  True, False])

In [15]:
fit.ranking_

array([1, 2, 4, 6, 5, 1, 1, 3])

In [16]:
from pandas import read_csv
from sklearn.tree import DecisionTreeClassifier

filename = '/content/pima-indians-diabetes.data.csv'
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
print(names)

dataframe = read_csv(filename, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]

model = DecisionTreeClassifier()
model.fit(X, Y)
print(model.feature_importances_)

['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
[0.07  0.325 0.091 0.018 0.037 0.238 0.119 0.103]
